### ISSUE TITLE
[Permission] Reduce permissions in manifest.json to Pontoon server + localizable Mozilla websites for contextual icons

### ISSUE THREAD

**Issue by Oymate** [MikkCZ/pontoon-addon#153]
### Steps to reproduce
1.Install from mozilla addon
2.Ask for permission
3.Permission wanted for all sites

### Actual behavior
Permission wanted for all sites

### Expected behavior
Only https://pontoon.mozilla.org/ is accessed

**Comment by MikkCZ** [comment]
Hi @Oymate.

Thank you for reaching out. It's actually not just pontoon.mozilla.org (or other Pontoon server configured in the extension settings) which is being accessed, but also other Mozilla websites. It's noted in the [privacy policy](https://github.com/MikkCZ/pontoon-addon/blob/master/PRIVACY.md) that this permission is needed for the contextual feature, which allows to highlight any text on localizable website, and then pivot to Pontoon. It looks like this

![](https://raw.githubusercontent.com/MikkCZ/pontoon-addon/a9dae699ab9ad3520a981fdbce8e54c46393e438/src/packages/intro/assets/img/context-buttons.png)

The reason to ask for all websites instead of an explicit list is that the list is quite long (risk of missing some) and possible UX issues when the the list is extended and the extension asks for more. The first reason may go away with #135 in the near future though.

Does this answer cover your issue? Is that OK if rephrase this issue a little and try to address it after #135 (hopefully during summer) and if the UX when a new item is added is not too terrible?

**Comment by Oymate** [comment]
Yeah, it's a backlog. Again thanks for the add-on :)
